# Generated by Django 5.0.4 on 2025-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetyear',
            options={},
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='description',
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='is_actual',
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='is_proposed',
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='budgetyear',
            name='year',
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='name',
            field=models.CharField(default='Unknown Year', max_length=100),
        ),
    ]
