# Generated by Django 5.1.6 on 2025-03-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableA', '0003_forms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
    ]
