# Generated by Django 5.1.6 on 2025-03-11 23:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableA', '0004_rename_forms_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='form',
            name='appropriation_source',
        ),
        migrations.RemoveField(
            model_name='form',
            name='department',
        ),
        migrations.RemoveField(
            model_name='form',
            name='operating_unit',
        ),
        migrations.RemoveField(
            model_name='form',
            name='year',
        ),
        migrations.AddField(
            model_name='appropriationtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appropriationtype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approriation_unit', to='tableA.department'),
        ),
        migrations.AddField(
            model_name='appropriationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='year', to='tableA.department'),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tableA.form'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.agency')),
                ('appropriation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.appropriationtype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.department')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.form')),
                ('operating_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.operatingunit')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='tableA.budgetyear')),
            ],
        ),
    ]
