# Generated by Django 5.0.4 on 2025-03-12 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableA', '0007_alter_appropriationtype_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationtype',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approriation_unit', to='tableA.department'),
        ),
    ]
