# Generated by Django 5.0.4 on 2025-03-12 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableA', '0008_alter_appropriationtype_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
